"""
Django settings for ferreteria_la_35 project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

SECRET_KEY = 'tu_clave_secreta_generada'
  

DEBUG = True  # Cambiar a False en producción

ALLOWED_HOSTS = ['tudominio.com', 'www.tudominio.com', 'dirección.ip.aqui']


# Aplicaciones instaladas
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',    # Tu aplicación de cuentas
    'about',       # Tu aplicación de acerca de mí
    'pages',       # Tu aplicación de páginas
    'productos',   # Opcional: Tu aplicación de productos
    'clientes',    # Opcional: Tu aplicación de clientes
]


# Configuración de la base de datos (SQLite en este ejemplo)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'nombre_basedatos',
        'USER': 'usuario_basedatos',
        'PASSWORD': 'contraseña_basedatos',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Configuración de archivos estáticos (CSS, JavaScript, imágenes, etc.)
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Configuración de plantillas (HTML)
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# Configuración de URL para redireccionar al login
LOGIN_REDIRECT_URL = '/'

# Configuración de URL para redireccionar al logout
LOGOUT_REDIRECT_URL = '/'

# Configuración del idioma y zona horaria
LANGUAGE_CODE = 'es'
TIME_ZONE = 'America/Bogota'

# Middleware para la aplicación de administración
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

