# Generated by Django 5.0.7 on 2024-07-20 00:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_page_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='created_at',
        ),
        migrations.AddField(
            model_name='page',
            name='publish_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
